data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  annotated_dir: "data/annotated"
  sources_csv: "data/sources.csv"

models:
  spacy_ner_dir: "models/spacy_ner"

pipeline:
  batch_size: 32
  max_length: 512

openai:
  api_key: ${OPENAI_API_KEY}
  model: "gpt-3.5-turbo"

sectors:
  - ldes
  - geothermal
  - carbon_capture
  - green_steel

database:
  host: localhost
  port: 5432
  name: ldes_data
  user: ldes_user
  password: password

ingestion:
  url_columns:
    - "url1"
    - "url2"
    - "url3"
  chunk_size: 50
  chunk_delay: 5